theme: jekyll-theme-minimal
title: Data wanderer
logo: /assets/img/logo.jpeg
description: A journal in data, machine learning and AI.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
google_analytics:
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one



